version: '3.9'
services:
  nodebb:
    image: ghcr.io/nodebb/nodebb:latest
    container_name: nodebb
    restart: unless-stopped
    ports:
      - '4567:4567'
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-config:/opt/config
      - ./install/docker/setup.json:/usr/src/app/setup.json
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    command: ['redis-server', '--appendonly', 'yes', '--loglevel', 'warning']
    volumes:
      - redis-data:/data

  mongo:
    image: 'mongo:7-jammy'
    restart: unless-stopped
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: nodebb
      MONGO_INITDB_DATABASE: nodebb
    volumes:
      - mongo-data:/data/db
      - ./install/docker/mongodb-user-init.js:/docker-entrypoint-initdb.d/user-init.js

volumes:
  mongo-data:
  redis-data:
  nodebb-build:
  nodebb-uploads:
  nodebb-config: